In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
df=pd.read_csv('Данные для тестового задания - Данные об аудитории.csv')

In [3]:
df.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [60]:
df['date'] = pd.to_datetime(df['date'])

In [61]:
start_date = '2023-11-01'
end_date = '2023-11-30'
mask = (df['date'] >= start_date) & (df['date'] <= end_date)
november_data = df[mask]

In [62]:
mau_november = november_data['user_id'].nunique()
print("MAU за ноябрь 2023:", mau_november)

MAU за ноябрь 2023: 7639

In [63]:
dau = df.groupby('date')['user_id'].count().reset_index()
print(dau)

         date  user_id
0  2023-11-01      623
1  2023-11-02      649
2  2023-11-03      573
3  2023-11-04      343
4  2023-11-05      350
5  2023-11-06      660
6  2023-11-07      629
7  2023-11-08      600
8  2023-11-09      661
9  2023-11-10      583
10 2023-11-11      354
11 2023-11-12      377
12 2023-11-13      646
13 2023-11-14      687
14 2023-11-15      690
15 2023-11-16      639
16 2023-11-17      585
17 2023-11-18      412
18 2023-11-19      378
19 2023-11-20      711
20 2023-11-21      651
21 2023-11-22      608
22 2023-11-23      632
23 2023-11-24      595
24 2023-11-25      366
25 2023-11-26      372
26 2023-11-27      589
27 2023-11-28      610
28 2023-11-29      621
29 2023-11-30      620

In [12]:
cohort_date = '2023-11-01'
cohort_users = df[df['date'] == cohort_date]['user_id'].unique()

# Проверяем, сколько из них вернулись 2 ноября
next_day = pd.to_datetime(cohort_date) + pd.Timedelta(days=1)
returned_users = df[(df['date'] == next_day) & (df['user_id'].isin(cohort_users))]['user_id'].nunique()

# D1 Retention в %
d1_retention = (returned_users / len(cohort_users)) * 100
print(f"D1 Retention для пользователей, пришедших {cohort_date}: {d1_retention:.2f}%")

D1 Retention для пользователей, пришедших 2023-11-01: 26.65%

In [15]:
total_users = november_data['user_id'].nunique()
converted_users = november_data[november_data['view_adverts'] > 0]['user_id'].nunique()
conversion = (converted_users / total_users) * 100
print(conversion)

46.31496269145176

In [16]:
views_per_user = november_data.groupby('user_id')['view_adverts'].sum()
avg_views=views_per_user.mean()
print(avg_views)

2.8687000916350307

In [17]:
total_users = 2000
promoters = 1200
detractors = 500
percent_promoters = (promoters / total_users) * 100
percent_detractors = (detractors / total_users) * 100
nps = percent_promoters - percent_detractors
print(nps)

35.0

In [43]:
df2 = pd.read_csv('Данные для тестового задания - Данные АБ тестов.csv')

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2835 entries, 0 to 2834
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   experiment_num    2835 non-null   int64
 1   experiment_group  2835 non-null   object
 2   user_id           2835 non-null   int64
 3   revenue           2835 non-null   int64
dtypes: int64(3), object(1)
memory usage: 88.7+ KB

In [35]:
df2.groupby(['experiment_num', 'experiment_group'])['user_id'].count()

experiment_num  experiment_group
1               control             465
                test                480
2               control             465
                test                480
3               control             465
                test                480
Name: user_id, dtype: int64

In [45]:
import numpy as np
from scipy import stats

df2['revenue_log'] = np.log1p(df['revenue'])

group_A = df2[df2['experiment_group'] == 'control']['revenue_log']
group_B = df2[df2['experiment_group'] == 'test']['revenue_log']

t_stat, p_value = stats.ttest_ind(group_A, group_B, equal_var=False)

print(p_value)

0.14162823300236288

In [47]:
df = pd.read_csv('Данные для тестового задания-листеры.csv')

In [48]:
df.head()

   user_id        date  cnt_adverts   age  cnt_contacts  revenue
0    100.0  2022-01-01          6.0  21.0         119.0     53.0
1    100.0  2022-01-02          2.0  21.0         200.0     18.0
2    100.0  2022-01-03          6.0  21.0         193.0     42.0
3    100.0  2022-01-04          2.0  21.0         143.0     38.0
4    100.0  2022-01-05          2.0  21.0         190.0     40.0

In [49]:
arpu = df.groupby('user_id')['revenue'].sum().mean()
print(arpu)

156.48387096774192

In [53]:
median=df['age'].median()
print(median)

28.0

In [55]:
from scipy import stats
import numpy as np

p1 = 1003 / 100047501
p2 = 1099 / 100001055

p_pool = (1003 + 1099) / (100047501 + 100001055)

se = np.sqrt(p_pool * (1 - p_pool) * (1/100047501 + 1/100001055))

z = (p2 - p1) / se
p_value = 2 * (1 - stats.norm.cdf(abs(z)))

print(p1,p2)
print(z, p_value)

1.0025237911739544e-05 1.0989884056723202e-05
2.1045506019397746 0.03533044544854258